sudo: false
language: generic

# quick hack to determine what tag is (improvements welcomed)
#     release: ^v(\d+|\.)*[^a-z]\d*$
# dev release: ^v(\d+|\.)*[a-z]\d*$

env:
  global:
    - PYENV_VERSION=3.6
    - PKG_TEST_GROUP="--test-group=all"
    - CHANS_DEV="-c pyviz/label/dev"
    - CHANS_REL="-c pyviz"
    - LABELS_DEV="--label=dev"
    - LABELS_REL="--label=dev --label=main"        
    # will be overridden later to upload only wheel for py27 (sdist from py36)
    - PIP_FORMATS="sdist bdist_wheel"

stages:
  - test
  - name: conda_dev_package
    if: tag =~ ^v(\d+|\.)*[a-z]\d*$
  - name: pip_dev_package
    if: tag =~ ^v(\d+|\.)*[a-z]\d*$
  - name: conda_package
    if: tag =~ ^v(\d+|\.)*[^a-z]\d*$
  - name: pip_package
    if: tag =~ ^v(\d+|\.)*[^a-z]\d*$

jobs:
  include:

  ########## TEST DEVELOPER INSTALL ##########  

  ## pip
  
  - &pip_default
    stage: test
    # (pyctdev requires itself to test itself)
    before_install:
      - pyenv install 3.6.3
      - pyenv global 3.6.3      
      - pip install -e .
    install: doit develop_install
    script:
      - doit test_all
      - doit --dir=examples/one test_all
      #- doit --dir=examples/two test_all

  ## conda

  - &conda_default
    stage: test
    env: PYCTDEV_ECOSYSTEM=conda
    before_install:
      - pyenv install 3.6.3
      - pyenv global 3.6.3
      ## install miniconda (using git pyctdev)
      - pip install -e . && doit miniconda_install && pip uninstall -y doit pyctdev && rm -f .doit.db
      - export PATH="$HOME/miniconda/bin:$PATH"
      - conda install -y "python=3.6" # required because conda-build isn't noarch, so otherwise causes python downgrade later on
      ## build conda package (using git pyctdev)
      - pip install -e . && doit ecosystem_setup && doit package_build $CHANNELS && pip uninstall -y doit pyctdev && rm -f .doit.db
      ## install conda package to use for rest of tests
      - conda install -y --use-local pyctdev
    install: doit develop_install
    script:
      - doit test_all
      - conda config --add channels file:///$HOME/miniconda/conda-bld
      - export PYCTDEV_SELF_CHANNEL="" # so the above channel will be used
      - doit --dir=examples/one test_all
      - doit --dir=examples/one test_export
      # TODO: still need to update conda stuff e.g. remove recipe
      - doit --dir=examples/two test_export

  ########## BUILD/TEST/UPLOAD END-USER PACKAGES ##########

  ##### pip

  # (pip ones are deliberately split up...upload 2.7 packages first so
  # that pypi displays 3's metadata; issue at pypa TODO)

  - &pip_pkg_default
    stage: pip_dev_package
    env: PYENV_VERSION=2.7 PYPI=testpypi PIP_FORMATS="bdist_wheel"
    before_install:
      - pip install -e .
      - doit ecosystem_setup
    install: doit package_build $PKG_TEST_GROUP --formats="$PIP_FORMATS" --sdist-run-tests
    script: doit package_upload -u ceball -p $PYPIPWD --pypi ${PYPI}

  - <<: *pip_pkg_default
    env: PYENV_VERSION=3.6 PYPI=testpypi

  - <<: *pip_pkg_default
    stage: pip_package
    env: PYENV_VERSION=2.7 PYPI=pypi PIP_FORMATS="bdist_wheel"

  - <<: *pip_pkg_default
    stage: pip_package
    env: PYENV_VERSION=3.6 PYPI=pypi


  ##### conda

  - &conda_pkg_default
    <<: *conda_default
    stage: conda_dev_package
    env: PYCTDEV_ECOSYSTEM=conda CHANS=$CHANS_DEV LABELS=$LABELS_DEV
    install: doit package_build $CHANS --test-python=py36 --test-python=py27 $PKG_TEST_GROUP
    script: doit package_upload --token=$CONDA_UPLOAD_TOKEN $LABELS

  - <<: *conda_pkg_default
    stage: conda_package
    env: PYCTDEV_ECOSYSTEM=conda CHANS=$CHANS_REL LABELS=$LABELS_REL
